---
# Source: demo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-server-web
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            memory: 1Gi
            cpu : 500m
          requests:
            memory: 100Mi
            cpu : 50m
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
          - name:  web-page
            mountPath:  /usr/share/nginx/html
      volumes:
        - name:  web-page
          configMap:
            name: maconfigmap
