replicaCount: 1
imagePullPolicy: Always

enableLog4j: true
enableShellInjection: true

web:
  image: crapi/crapi-web
  port: 80
  ingress:
    enabled: true
    hosts:
      - vulnerable.crapi.localhost
    annotations:
      nginx.ingress.kubernetes.io/enable-modsecurity: "false"
identity:
  image: crapi/crapi-identity
  port: 8080
community:
  image: crapi/crapi-community
  port: 8087
workshop:
  image: crapi/crapi-workshop
  port: 8000
mailhog:
  image: crapi/mailhog
  webPort: 8025
  ingress:
    enabled: true
    hosts:
      - vulnerable.mailhog.crapi.localhost
    annotations:
      nginx.ingress.kubernetes.io/enable-modsecurity: "false"
mongodb:
  image: mongo
  version: 5.0
postgresdb:
  image: postgres
  version: 14
