kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: waitfor-reader-{{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["services","pods"]
  verbs: ["get", "watch", "list"]
